# .github/workflows/ci.yml
name: CI

on:
  push:       # run on every push to any branch

jobs:
  check_working_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setting up the Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installing the dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Running training script
        run: python train.py

      - name: Running test script
        run: python test.py
